version: '3'
services:
  strapi:
    image: strapi_image
    command: ['npm', 'run', 'develop']
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    ports:
      - 1337:1337
    depends_on:
      - redis
      - mysql-container # Ensure this matches the name of your MySQL service
      - keycloak
  redis:
    image: redis
    ports:
      - '6379:6379'
  mysql-container:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
      - default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

  keycloak:
    image: jboss/keycloak:9.0.2
    container_name: keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql-container
      DB_DATABASE: strapi
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: root21
      KEYCLOAK_PASSWORD: root21
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysql-container
