version: '3'
services:
  strapi:
    image: strapi_image
    command: [ 'npm', 'run', 'develop' ]
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    ports:
      - 1337:1337
    depends_on:
      - redis
      - mysql-container
      - keycloak
  redis:
    image: redis
    ports:
      - '6379:6379'
  mysql-container:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
      - default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    command: start-dev
    container_name: keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql-container
      DB_DATABASE: strapi
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_ADMIN: root
      KEYCLOAK_ADMIN_PASSWORD: root
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysql-container
